project:
  type: website
  output-dir: docs/

website:
  title: "Leandro Vento"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portifolio.qmd
        text: Portifólio
    right:
      - icon: github
        href: https://www.github.com/leandro-vento

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

